project_name: polycrate

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

#region: us-west-1
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X polycrate/cmd.version={{.Version}} -X polycrate/cmd.commit={{.Commit}} -X polycrate/cmd.date={{.CommitDate}} -X polycrate/cmd.builtBy=ayedo
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  skip: true
  use: github
  filters:
    exclude:
      - "^test:"
      - "typo"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
dockers:
  - image_templates:
      - "cargo.ayedo.cloud/library/polycrate:{{ .Version }}-amd64"
      - "cargo.ayedo.cloud/library/polycrate:v{{ .Major }}-amd64"
      - "cargo.ayedo.cloud/library/polycrate:v{{ .Major }}.{{ .Minor }}-amd64"
      - "cargo.ayedo.cloud/library/polycrate:latest-amd64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=AWS_ARCH=x86_64"
    extra_files:
      - python-requirements.txt
      - ansible-requirements.yml
      - hack/ansible/plugins/vars/polycrate_vars.py
      - hack/ansible/inventory
      - hack/poly-utils
  - image_templates:
      - "cargo.ayedo.cloud/library/polycrate:{{ .Version }}-arm64v8"
      - "cargo.ayedo.cloud/library/polycrate:v{{ .Major }}-arm64v8"
      - "cargo.ayedo.cloud/library/polycrate:v{{ .Major }}.{{ .Minor }}-arm64v8"
      - "cargo.ayedo.cloud/library/polycrate:latest-arm64v8"
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64/v8"
      - "--build-arg=AWS_ARCH=aarch64"
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - python-requirements.txt
      - ansible-requirements.yml
      - hack/ansible/plugins/vars/polycrate_vars.py
      - hack/ansible/inventory
      - hack/poly-utils
docker_manifests:
  - name_template: cargo.ayedo.cloud/library/polycrate:{{ .Version }}
    image_templates:
      - cargo.ayedo.cloud/library/polycrate:{{ .Version }}-amd64
      - cargo.ayedo.cloud/library/polycrate:{{ .Version }}-arm64v8
  - name_template: cargo.ayedo.cloud/library/polycrate:{{ .Major }}
    image_templates:
      - cargo.ayedo.cloud/library/polycrate:v{{ .Major }}-amd64
      - cargo.ayedo.cloud/library/polycrate:v{{ .Major }}-arm64v8
  - name_template: cargo.ayedo.cloud/library/polycrate:{{ .Major }}.{{ .Minor }}
    image_templates:
      - cargo.ayedo.cloud/library/polycrate:v{{ .Major }}.{{ .Minor }}-amd64
      - cargo.ayedo.cloud/library/polycrate:v{{ .Major }}.{{ .Minor }}-arm64v8
  - name_template: cargo.ayedo.cloud/library/polycrate:latest
    image_templates:
      - cargo.ayedo.cloud/library/polycrate:latest-amd64
      - cargo.ayedo.cloud/library/polycrate:latest-arm64v8
release:
  disable: true
  github:
    owner: polycrate
    name: polycrate
  header: |
    ## Polycrate v{{ .Version }} ({{ .Date }})

  footer: |
    ## Docker Images

    - `cargo.ayedo.cloud/library/polycrate:{{ .Version }}`
    - `cargo.ayedo.cloud/library/polycrate:{{ .Major }}.{{ .Minor }}`
    - `cargo.ayedo.cloud/library/polycrate:{{ .Major }}`
    - `cargo.ayedo.cloud/library/polycrate:latest`

    ## Get support

    - [Discord](https://discord.gg/8cQZfXWeXP)
    - [GitHub Issues](https://github.com/polycrate/polycrate/issues)
